CREATE TABLE IF NOT EXISTS permissoes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descricao varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS usuarios (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(255) DEFAULT NULL,
    sobrenome varchar(255) DEFAULT NULL,
    username varchar(255) DEFAULT NULL,
    password varchar(255) DEFAULT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS usuarios_permissoes (
    id_usuario bigint NOT NULL,
    id_permissao bigint NOT NULL,
    PRIMARY KEY (id_usuario, id_permissao),
    CONSTRAINT usuario_permissao_fk FOREIGN KEY (id_usuario) REFERENCES usuarios (id),
    CONSTRAINT usuario_permissao_permissao FOREIGN KEY (id_permissao) REFERENCES permissoes (id)
);